// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ModerationBans   string
	ModerationCases  string
	ModerationConfig string
	ModerationMutes  string
}{
	ModerationBans:   "moderation_bans",
	ModerationCases:  "moderation_cases",
	ModerationConfig: "moderation_config",
	ModerationMutes:  "moderation_mutes",
}
