// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ModerationConfig is an object representing the database table.
type ModerationConfig struct {
	GuildID                 string            `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	Enabled                 bool              `boil:"enabled" json:"enabled" toml:"enabled" yaml:"enabled"`
	EnabledTriggerDeletion  bool              `boil:"enabled_trigger_deletion" json:"enabled_trigger_deletion" toml:"enabled_trigger_deletion" yaml:"enabled_trigger_deletion"`
	SecondsToDeleteTrigger  int               `boil:"seconds_to_delete_trigger" json:"seconds_to_delete_trigger" toml:"seconds_to_delete_trigger" yaml:"seconds_to_delete_trigger"`
	EnabledResponseDeletion bool              `boil:"enabled_response_deletion" json:"enabled_response_deletion" toml:"enabled_response_deletion" yaml:"enabled_response_deletion"`
	SecondsToDeleteResponse int               `boil:"seconds_to_delete_response" json:"seconds_to_delete_response" toml:"seconds_to_delete_response" yaml:"seconds_to_delete_response"`
	ModLog                  null.String       `boil:"mod_log" json:"mod_log,omitempty" toml:"mod_log" yaml:"mod_log,omitempty"`
	ManageMuteRole          bool              `boil:"manage_mute_role" json:"manage_mute_role" toml:"manage_mute_role" yaml:"manage_mute_role"`
	MuteRole                null.String       `boil:"mute_role" json:"mute_role,omitempty" toml:"mute_role" yaml:"mute_role,omitempty"`
	UpdateRoles             types.StringArray `boil:"update_roles" json:"update_roles,omitempty" toml:"update_roles" yaml:"update_roles,omitempty"`
	LastCaseID              int64             `boil:"last_case_id" json:"last_case_id" toml:"last_case_id" yaml:"last_case_id"`

	R *moderationConfigR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L moderationConfigL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ModerationConfigColumns = struct {
	GuildID                 string
	Enabled                 string
	EnabledTriggerDeletion  string
	SecondsToDeleteTrigger  string
	EnabledResponseDeletion string
	SecondsToDeleteResponse string
	ModLog                  string
	ManageMuteRole          string
	MuteRole                string
	UpdateRoles             string
	LastCaseID              string
}{
	GuildID:                 "guild_id",
	Enabled:                 "enabled",
	EnabledTriggerDeletion:  "enabled_trigger_deletion",
	SecondsToDeleteTrigger:  "seconds_to_delete_trigger",
	EnabledResponseDeletion: "enabled_response_deletion",
	SecondsToDeleteResponse: "seconds_to_delete_response",
	ModLog:                  "mod_log",
	ManageMuteRole:          "manage_mute_role",
	MuteRole:                "mute_role",
	UpdateRoles:             "update_roles",
	LastCaseID:              "last_case_id",
}

var ModerationConfigTableColumns = struct {
	GuildID                 string
	Enabled                 string
	EnabledTriggerDeletion  string
	SecondsToDeleteTrigger  string
	EnabledResponseDeletion string
	SecondsToDeleteResponse string
	ModLog                  string
	ManageMuteRole          string
	MuteRole                string
	UpdateRoles             string
	LastCaseID              string
}{
	GuildID:                 "moderation_config.guild_id",
	Enabled:                 "moderation_config.enabled",
	EnabledTriggerDeletion:  "moderation_config.enabled_trigger_deletion",
	SecondsToDeleteTrigger:  "moderation_config.seconds_to_delete_trigger",
	EnabledResponseDeletion: "moderation_config.enabled_response_deletion",
	SecondsToDeleteResponse: "moderation_config.seconds_to_delete_response",
	ModLog:                  "moderation_config.mod_log",
	ManageMuteRole:          "moderation_config.manage_mute_role",
	MuteRole:                "moderation_config.mute_role",
	UpdateRoles:             "moderation_config.update_roles",
	LastCaseID:              "moderation_config.last_case_id",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_StringArray struct{ field string }

func (w whereHelpertypes_StringArray) EQ(x types.StringArray) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpertypes_StringArray) NEQ(x types.StringArray) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpertypes_StringArray) LT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_StringArray) LTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_StringArray) GT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_StringArray) GTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpertypes_StringArray) IsNull() qm.QueryMod { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpertypes_StringArray) IsNotNull() qm.QueryMod {
	return qmhelper.WhereIsNotNull(w.field)
}

var ModerationConfigWhere = struct {
	GuildID                 whereHelperstring
	Enabled                 whereHelperbool
	EnabledTriggerDeletion  whereHelperbool
	SecondsToDeleteTrigger  whereHelperint
	EnabledResponseDeletion whereHelperbool
	SecondsToDeleteResponse whereHelperint
	ModLog                  whereHelpernull_String
	ManageMuteRole          whereHelperbool
	MuteRole                whereHelpernull_String
	UpdateRoles             whereHelpertypes_StringArray
	LastCaseID              whereHelperint64
}{
	GuildID:                 whereHelperstring{field: "\"moderation_config\".\"guild_id\""},
	Enabled:                 whereHelperbool{field: "\"moderation_config\".\"enabled\""},
	EnabledTriggerDeletion:  whereHelperbool{field: "\"moderation_config\".\"enabled_trigger_deletion\""},
	SecondsToDeleteTrigger:  whereHelperint{field: "\"moderation_config\".\"seconds_to_delete_trigger\""},
	EnabledResponseDeletion: whereHelperbool{field: "\"moderation_config\".\"enabled_response_deletion\""},
	SecondsToDeleteResponse: whereHelperint{field: "\"moderation_config\".\"seconds_to_delete_response\""},
	ModLog:                  whereHelpernull_String{field: "\"moderation_config\".\"mod_log\""},
	ManageMuteRole:          whereHelperbool{field: "\"moderation_config\".\"manage_mute_role\""},
	MuteRole:                whereHelpernull_String{field: "\"moderation_config\".\"mute_role\""},
	UpdateRoles:             whereHelpertypes_StringArray{field: "\"moderation_config\".\"update_roles\""},
	LastCaseID:              whereHelperint64{field: "\"moderation_config\".\"last_case_id\""},
}

// ModerationConfigRels is where relationship names are stored.
var ModerationConfigRels = struct {
	GuildModerationBans        string
	GuildModerationCases       string
	GuildModerationConfigRoles string
	GuildModerationMutes       string
}{
	GuildModerationBans:        "GuildModerationBans",
	GuildModerationCases:       "GuildModerationCases",
	GuildModerationConfigRoles: "GuildModerationConfigRoles",
	GuildModerationMutes:       "GuildModerationMutes",
}

// moderationConfigR is where relationships are stored.
type moderationConfigR struct {
	GuildModerationBans        ModerationBanSlice        `boil:"GuildModerationBans" json:"GuildModerationBans" toml:"GuildModerationBans" yaml:"GuildModerationBans"`
	GuildModerationCases       ModerationCaseSlice       `boil:"GuildModerationCases" json:"GuildModerationCases" toml:"GuildModerationCases" yaml:"GuildModerationCases"`
	GuildModerationConfigRoles ModerationConfigRoleSlice `boil:"GuildModerationConfigRoles" json:"GuildModerationConfigRoles" toml:"GuildModerationConfigRoles" yaml:"GuildModerationConfigRoles"`
	GuildModerationMutes       ModerationMuteSlice       `boil:"GuildModerationMutes" json:"GuildModerationMutes" toml:"GuildModerationMutes" yaml:"GuildModerationMutes"`
}

// NewStruct creates a new relationship struct
func (*moderationConfigR) NewStruct() *moderationConfigR {
	return &moderationConfigR{}
}

func (o *ModerationConfig) GetGuildModerationBans() ModerationBanSlice {
	if o == nil {
		return nil
	}

	return o.R.GetGuildModerationBans()
}

func (r *moderationConfigR) GetGuildModerationBans() ModerationBanSlice {
	if r == nil {
		return nil
	}

	return r.GuildModerationBans
}

func (o *ModerationConfig) GetGuildModerationCases() ModerationCaseSlice {
	if o == nil {
		return nil
	}

	return o.R.GetGuildModerationCases()
}

func (r *moderationConfigR) GetGuildModerationCases() ModerationCaseSlice {
	if r == nil {
		return nil
	}

	return r.GuildModerationCases
}

func (o *ModerationConfig) GetGuildModerationConfigRoles() ModerationConfigRoleSlice {
	if o == nil {
		return nil
	}

	return o.R.GetGuildModerationConfigRoles()
}

func (r *moderationConfigR) GetGuildModerationConfigRoles() ModerationConfigRoleSlice {
	if r == nil {
		return nil
	}

	return r.GuildModerationConfigRoles
}

func (o *ModerationConfig) GetGuildModerationMutes() ModerationMuteSlice {
	if o == nil {
		return nil
	}

	return o.R.GetGuildModerationMutes()
}

func (r *moderationConfigR) GetGuildModerationMutes() ModerationMuteSlice {
	if r == nil {
		return nil
	}

	return r.GuildModerationMutes
}

// moderationConfigL is where Load methods for each relationship are stored.
type moderationConfigL struct{}

var (
	moderationConfigAllColumns            = []string{"guild_id", "enabled", "enabled_trigger_deletion", "seconds_to_delete_trigger", "enabled_response_deletion", "seconds_to_delete_response", "mod_log", "manage_mute_role", "mute_role", "update_roles", "last_case_id"}
	moderationConfigColumnsWithoutDefault = []string{"guild_id"}
	moderationConfigColumnsWithDefault    = []string{"enabled", "enabled_trigger_deletion", "seconds_to_delete_trigger", "enabled_response_deletion", "seconds_to_delete_response", "mod_log", "manage_mute_role", "mute_role", "update_roles", "last_case_id"}
	moderationConfigPrimaryKeyColumns     = []string{"guild_id"}
	moderationConfigGeneratedColumns      = []string{}
)

type (
	// ModerationConfigSlice is an alias for a slice of pointers to ModerationConfig.
	// This should almost always be used instead of []ModerationConfig.
	ModerationConfigSlice []*ModerationConfig

	moderationConfigQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	moderationConfigType                 = reflect.TypeOf(&ModerationConfig{})
	moderationConfigMapping              = queries.MakeStructMapping(moderationConfigType)
	moderationConfigPrimaryKeyMapping, _ = queries.BindMapping(moderationConfigType, moderationConfigMapping, moderationConfigPrimaryKeyColumns)
	moderationConfigInsertCacheMut       sync.RWMutex
	moderationConfigInsertCache          = make(map[string]insertCache)
	moderationConfigUpdateCacheMut       sync.RWMutex
	moderationConfigUpdateCache          = make(map[string]updateCache)
	moderationConfigUpsertCacheMut       sync.RWMutex
	moderationConfigUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single moderationConfig record from the query using the global executor.
func (q moderationConfigQuery) OneG(ctx context.Context) (*ModerationConfig, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single moderationConfig record from the query.
func (q moderationConfigQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ModerationConfig, error) {
	o := &ModerationConfig{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for moderation_config")
	}

	return o, nil
}

// AllG returns all ModerationConfig records from the query using the global executor.
func (q moderationConfigQuery) AllG(ctx context.Context) (ModerationConfigSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ModerationConfig records from the query.
func (q moderationConfigQuery) All(ctx context.Context, exec boil.ContextExecutor) (ModerationConfigSlice, error) {
	var o []*ModerationConfig

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ModerationConfig slice")
	}

	return o, nil
}

// CountG returns the count of all ModerationConfig records in the query using the global executor
func (q moderationConfigQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ModerationConfig records in the query.
func (q moderationConfigQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count moderation_config rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q moderationConfigQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q moderationConfigQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if moderation_config exists")
	}

	return count > 0, nil
}

// GuildModerationBans retrieves all the moderation_ban's ModerationBans with an executor via guild_id column.
func (o *ModerationConfig) GuildModerationBans(mods ...qm.QueryMod) moderationBanQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"moderation_bans\".\"guild_id\"=?", o.GuildID),
	)

	return ModerationBans(queryMods...)
}

// GuildModerationCases retrieves all the moderation_case's ModerationCases with an executor via guild_id column.
func (o *ModerationConfig) GuildModerationCases(mods ...qm.QueryMod) moderationCaseQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"moderation_cases\".\"guild_id\"=?", o.GuildID),
	)

	return ModerationCases(queryMods...)
}

// GuildModerationConfigRoles retrieves all the moderation_config_role's ModerationConfigRoles with an executor via guild_id column.
func (o *ModerationConfig) GuildModerationConfigRoles(mods ...qm.QueryMod) moderationConfigRoleQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"moderation_config_roles\".\"guild_id\"=?", o.GuildID),
	)

	return ModerationConfigRoles(queryMods...)
}

// GuildModerationMutes retrieves all the moderation_mute's ModerationMutes with an executor via guild_id column.
func (o *ModerationConfig) GuildModerationMutes(mods ...qm.QueryMod) moderationMuteQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"moderation_mutes\".\"guild_id\"=?", o.GuildID),
	)

	return ModerationMutes(queryMods...)
}

// LoadGuildModerationBans allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (moderationConfigL) LoadGuildModerationBans(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModerationConfig interface{}, mods queries.Applicator) error {
	var slice []*ModerationConfig
	var object *ModerationConfig

	if singular {
		var ok bool
		object, ok = maybeModerationConfig.(*ModerationConfig)
		if !ok {
			object = new(ModerationConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModerationConfig))
			}
		}
	} else {
		s, ok := maybeModerationConfig.(*[]*ModerationConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModerationConfig))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &moderationConfigR{}
		}
		args[object.GuildID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moderationConfigR{}
			}
			args[obj.GuildID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`moderation_bans`),
		qm.WhereIn(`moderation_bans.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load moderation_bans")
	}

	var resultSlice []*ModerationBan
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice moderation_bans")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on moderation_bans")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for moderation_bans")
	}

	if singular {
		object.R.GuildModerationBans = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &moderationBanR{}
			}
			foreign.R.Guild = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.GuildID == foreign.GuildID {
				local.R.GuildModerationBans = append(local.R.GuildModerationBans, foreign)
				if foreign.R == nil {
					foreign.R = &moderationBanR{}
				}
				foreign.R.Guild = local
				break
			}
		}
	}

	return nil
}

// LoadGuildModerationCases allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (moderationConfigL) LoadGuildModerationCases(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModerationConfig interface{}, mods queries.Applicator) error {
	var slice []*ModerationConfig
	var object *ModerationConfig

	if singular {
		var ok bool
		object, ok = maybeModerationConfig.(*ModerationConfig)
		if !ok {
			object = new(ModerationConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModerationConfig))
			}
		}
	} else {
		s, ok := maybeModerationConfig.(*[]*ModerationConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModerationConfig))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &moderationConfigR{}
		}
		args[object.GuildID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moderationConfigR{}
			}
			args[obj.GuildID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`moderation_cases`),
		qm.WhereIn(`moderation_cases.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load moderation_cases")
	}

	var resultSlice []*ModerationCase
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice moderation_cases")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on moderation_cases")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for moderation_cases")
	}

	if singular {
		object.R.GuildModerationCases = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &moderationCaseR{}
			}
			foreign.R.Guild = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.GuildID == foreign.GuildID {
				local.R.GuildModerationCases = append(local.R.GuildModerationCases, foreign)
				if foreign.R == nil {
					foreign.R = &moderationCaseR{}
				}
				foreign.R.Guild = local
				break
			}
		}
	}

	return nil
}

// LoadGuildModerationConfigRoles allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (moderationConfigL) LoadGuildModerationConfigRoles(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModerationConfig interface{}, mods queries.Applicator) error {
	var slice []*ModerationConfig
	var object *ModerationConfig

	if singular {
		var ok bool
		object, ok = maybeModerationConfig.(*ModerationConfig)
		if !ok {
			object = new(ModerationConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModerationConfig))
			}
		}
	} else {
		s, ok := maybeModerationConfig.(*[]*ModerationConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModerationConfig))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &moderationConfigR{}
		}
		args[object.GuildID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moderationConfigR{}
			}
			args[obj.GuildID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`moderation_config_roles`),
		qm.WhereIn(`moderation_config_roles.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load moderation_config_roles")
	}

	var resultSlice []*ModerationConfigRole
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice moderation_config_roles")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on moderation_config_roles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for moderation_config_roles")
	}

	if singular {
		object.R.GuildModerationConfigRoles = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &moderationConfigRoleR{}
			}
			foreign.R.Guild = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.GuildID == foreign.GuildID {
				local.R.GuildModerationConfigRoles = append(local.R.GuildModerationConfigRoles, foreign)
				if foreign.R == nil {
					foreign.R = &moderationConfigRoleR{}
				}
				foreign.R.Guild = local
				break
			}
		}
	}

	return nil
}

// LoadGuildModerationMutes allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (moderationConfigL) LoadGuildModerationMutes(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModerationConfig interface{}, mods queries.Applicator) error {
	var slice []*ModerationConfig
	var object *ModerationConfig

	if singular {
		var ok bool
		object, ok = maybeModerationConfig.(*ModerationConfig)
		if !ok {
			object = new(ModerationConfig)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModerationConfig))
			}
		}
	} else {
		s, ok := maybeModerationConfig.(*[]*ModerationConfig)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModerationConfig)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModerationConfig))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &moderationConfigR{}
		}
		args[object.GuildID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moderationConfigR{}
			}
			args[obj.GuildID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`moderation_mutes`),
		qm.WhereIn(`moderation_mutes.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load moderation_mutes")
	}

	var resultSlice []*ModerationMute
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice moderation_mutes")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on moderation_mutes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for moderation_mutes")
	}

	if singular {
		object.R.GuildModerationMutes = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &moderationMuteR{}
			}
			foreign.R.Guild = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.GuildID == foreign.GuildID {
				local.R.GuildModerationMutes = append(local.R.GuildModerationMutes, foreign)
				if foreign.R == nil {
					foreign.R = &moderationMuteR{}
				}
				foreign.R.Guild = local
				break
			}
		}
	}

	return nil
}

// AddGuildModerationBansG adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationBans.
// Sets related.R.Guild appropriately.
// Uses the global database handle.
func (o *ModerationConfig) AddGuildModerationBansG(ctx context.Context, insert bool, related ...*ModerationBan) error {
	return o.AddGuildModerationBans(ctx, boil.GetContextDB(), insert, related...)
}

// AddGuildModerationBans adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationBans.
// Sets related.R.Guild appropriately.
func (o *ModerationConfig) AddGuildModerationBans(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ModerationBan) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.GuildID = o.GuildID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"moderation_bans\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
				strmangle.WhereClause("\"", "\"", 2, moderationBanPrimaryKeyColumns),
			)
			values := []interface{}{o.GuildID, rel.GuildID, rel.UserID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.GuildID = o.GuildID
		}
	}

	if o.R == nil {
		o.R = &moderationConfigR{
			GuildModerationBans: related,
		}
	} else {
		o.R.GuildModerationBans = append(o.R.GuildModerationBans, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &moderationBanR{
				Guild: o,
			}
		} else {
			rel.R.Guild = o
		}
	}
	return nil
}

// AddGuildModerationCasesG adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationCases.
// Sets related.R.Guild appropriately.
// Uses the global database handle.
func (o *ModerationConfig) AddGuildModerationCasesG(ctx context.Context, insert bool, related ...*ModerationCase) error {
	return o.AddGuildModerationCases(ctx, boil.GetContextDB(), insert, related...)
}

// AddGuildModerationCases adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationCases.
// Sets related.R.Guild appropriately.
func (o *ModerationConfig) AddGuildModerationCases(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ModerationCase) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.GuildID = o.GuildID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"moderation_cases\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
				strmangle.WhereClause("\"", "\"", 2, moderationCasePrimaryKeyColumns),
			)
			values := []interface{}{o.GuildID, rel.GuildID, rel.CaseID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.GuildID = o.GuildID
		}
	}

	if o.R == nil {
		o.R = &moderationConfigR{
			GuildModerationCases: related,
		}
	} else {
		o.R.GuildModerationCases = append(o.R.GuildModerationCases, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &moderationCaseR{
				Guild: o,
			}
		} else {
			rel.R.Guild = o
		}
	}
	return nil
}

// AddGuildModerationConfigRolesG adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationConfigRoles.
// Sets related.R.Guild appropriately.
// Uses the global database handle.
func (o *ModerationConfig) AddGuildModerationConfigRolesG(ctx context.Context, insert bool, related ...*ModerationConfigRole) error {
	return o.AddGuildModerationConfigRoles(ctx, boil.GetContextDB(), insert, related...)
}

// AddGuildModerationConfigRoles adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationConfigRoles.
// Sets related.R.Guild appropriately.
func (o *ModerationConfig) AddGuildModerationConfigRoles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ModerationConfigRole) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.GuildID = o.GuildID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"moderation_config_roles\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
				strmangle.WhereClause("\"", "\"", 2, moderationConfigRolePrimaryKeyColumns),
			)
			values := []interface{}{o.GuildID, rel.ActionType, rel.RoleID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.GuildID = o.GuildID
		}
	}

	if o.R == nil {
		o.R = &moderationConfigR{
			GuildModerationConfigRoles: related,
		}
	} else {
		o.R.GuildModerationConfigRoles = append(o.R.GuildModerationConfigRoles, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &moderationConfigRoleR{
				Guild: o,
			}
		} else {
			rel.R.Guild = o
		}
	}
	return nil
}

// AddGuildModerationMutesG adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationMutes.
// Sets related.R.Guild appropriately.
// Uses the global database handle.
func (o *ModerationConfig) AddGuildModerationMutesG(ctx context.Context, insert bool, related ...*ModerationMute) error {
	return o.AddGuildModerationMutes(ctx, boil.GetContextDB(), insert, related...)
}

// AddGuildModerationMutes adds the given related objects to the existing relationships
// of the moderation_config, optionally inserting them as new records.
// Appends related to o.R.GuildModerationMutes.
// Sets related.R.Guild appropriately.
func (o *ModerationConfig) AddGuildModerationMutes(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ModerationMute) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.GuildID = o.GuildID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"moderation_mutes\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
				strmangle.WhereClause("\"", "\"", 2, moderationMutePrimaryKeyColumns),
			)
			values := []interface{}{o.GuildID, rel.GuildID, rel.UserID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.GuildID = o.GuildID
		}
	}

	if o.R == nil {
		o.R = &moderationConfigR{
			GuildModerationMutes: related,
		}
	} else {
		o.R.GuildModerationMutes = append(o.R.GuildModerationMutes, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &moderationMuteR{
				Guild: o,
			}
		} else {
			rel.R.Guild = o
		}
	}
	return nil
}

// ModerationConfigs retrieves all the records using an executor.
func ModerationConfigs(mods ...qm.QueryMod) moderationConfigQuery {
	mods = append(mods, qm.From("\"moderation_config\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"moderation_config\".*"})
	}

	return moderationConfigQuery{q}
}

// FindModerationConfigG retrieves a single record by ID.
func FindModerationConfigG(ctx context.Context, guildID string, selectCols ...string) (*ModerationConfig, error) {
	return FindModerationConfig(ctx, boil.GetContextDB(), guildID, selectCols...)
}

// FindModerationConfig retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindModerationConfig(ctx context.Context, exec boil.ContextExecutor, guildID string, selectCols ...string) (*ModerationConfig, error) {
	moderationConfigObj := &ModerationConfig{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"moderation_config\" where \"guild_id\"=$1", sel,
	)

	q := queries.Raw(query, guildID)

	err := q.Bind(ctx, exec, moderationConfigObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from moderation_config")
	}

	return moderationConfigObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ModerationConfig) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ModerationConfig) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no moderation_config provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(moderationConfigColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	moderationConfigInsertCacheMut.RLock()
	cache, cached := moderationConfigInsertCache[key]
	moderationConfigInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			moderationConfigAllColumns,
			moderationConfigColumnsWithDefault,
			moderationConfigColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(moderationConfigType, moderationConfigMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(moderationConfigType, moderationConfigMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"moderation_config\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"moderation_config\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into moderation_config")
	}

	if !cached {
		moderationConfigInsertCacheMut.Lock()
		moderationConfigInsertCache[key] = cache
		moderationConfigInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single ModerationConfig record using the global executor.
// See Update for more documentation.
func (o *ModerationConfig) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ModerationConfig.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ModerationConfig) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	moderationConfigUpdateCacheMut.RLock()
	cache, cached := moderationConfigUpdateCache[key]
	moderationConfigUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			moderationConfigAllColumns,
			moderationConfigPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update moderation_config, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"moderation_config\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, moderationConfigPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(moderationConfigType, moderationConfigMapping, append(wl, moderationConfigPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update moderation_config row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for moderation_config")
	}

	if !cached {
		moderationConfigUpdateCacheMut.Lock()
		moderationConfigUpdateCache[key] = cache
		moderationConfigUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q moderationConfigQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q moderationConfigQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for moderation_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for moderation_config")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ModerationConfigSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ModerationConfigSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"moderation_config\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, moderationConfigPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in moderationConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all moderationConfig")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ModerationConfig) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ModerationConfig) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no moderation_config provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(moderationConfigColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	moderationConfigUpsertCacheMut.RLock()
	cache, cached := moderationConfigUpsertCache[key]
	moderationConfigUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			moderationConfigAllColumns,
			moderationConfigColumnsWithDefault,
			moderationConfigColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			moderationConfigAllColumns,
			moderationConfigPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert moderation_config, could not build update column list")
		}

		ret := strmangle.SetComplement(moderationConfigAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(moderationConfigPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert moderation_config, could not build conflict column list")
			}

			conflict = make([]string, len(moderationConfigPrimaryKeyColumns))
			copy(conflict, moderationConfigPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"moderation_config\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(moderationConfigType, moderationConfigMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(moderationConfigType, moderationConfigMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert moderation_config")
	}

	if !cached {
		moderationConfigUpsertCacheMut.Lock()
		moderationConfigUpsertCache[key] = cache
		moderationConfigUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single ModerationConfig record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ModerationConfig) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ModerationConfig record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ModerationConfig) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ModerationConfig provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), moderationConfigPrimaryKeyMapping)
	sql := "DELETE FROM \"moderation_config\" WHERE \"guild_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from moderation_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for moderation_config")
	}

	return rowsAff, nil
}

func (q moderationConfigQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q moderationConfigQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no moderationConfigQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderation_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_config")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ModerationConfigSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ModerationConfigSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"moderation_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationConfigPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderationConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_config")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ModerationConfig) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no ModerationConfig provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ModerationConfig) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindModerationConfig(ctx, exec, o.GuildID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationConfigSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty ModerationConfigSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationConfigSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ModerationConfigSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"moderation_config\".* FROM \"moderation_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationConfigPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ModerationConfigSlice")
	}

	*o = slice

	return nil
}

// ModerationConfigExistsG checks if the ModerationConfig row exists.
func ModerationConfigExistsG(ctx context.Context, guildID string) (bool, error) {
	return ModerationConfigExists(ctx, boil.GetContextDB(), guildID)
}

// ModerationConfigExists checks if the ModerationConfig row exists.
func ModerationConfigExists(ctx context.Context, exec boil.ContextExecutor, guildID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"moderation_config\" where \"guild_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID)
	}
	row := exec.QueryRowContext(ctx, sql, guildID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if moderation_config exists")
	}

	return exists, nil
}

// Exists checks if the ModerationConfig row exists.
func (o *ModerationConfig) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ModerationConfigExists(ctx, exec, o.GuildID)
}
