// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ModerationConfigRole is an object representing the database table.
type ModerationConfigRole struct {
	GuildID    string `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	ActionType string `boil:"action_type" json:"action_type" toml:"action_type" yaml:"action_type"`
	RoleID     string `boil:"role_id" json:"role_id" toml:"role_id" yaml:"role_id"`

	R *moderationConfigRoleR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L moderationConfigRoleL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ModerationConfigRoleColumns = struct {
	GuildID    string
	ActionType string
	RoleID     string
}{
	GuildID:    "guild_id",
	ActionType: "action_type",
	RoleID:     "role_id",
}

var ModerationConfigRoleTableColumns = struct {
	GuildID    string
	ActionType string
	RoleID     string
}{
	GuildID:    "moderation_config_roles.guild_id",
	ActionType: "moderation_config_roles.action_type",
	RoleID:     "moderation_config_roles.role_id",
}

// Generated where

var ModerationConfigRoleWhere = struct {
	GuildID    whereHelperstring
	ActionType whereHelperstring
	RoleID     whereHelperstring
}{
	GuildID:    whereHelperstring{field: "\"moderation_config_roles\".\"guild_id\""},
	ActionType: whereHelperstring{field: "\"moderation_config_roles\".\"action_type\""},
	RoleID:     whereHelperstring{field: "\"moderation_config_roles\".\"role_id\""},
}

// ModerationConfigRoleRels is where relationship names are stored.
var ModerationConfigRoleRels = struct {
	Guild string
}{
	Guild: "Guild",
}

// moderationConfigRoleR is where relationships are stored.
type moderationConfigRoleR struct {
	Guild *ModerationConfig `boil:"Guild" json:"Guild" toml:"Guild" yaml:"Guild"`
}

// NewStruct creates a new relationship struct
func (*moderationConfigRoleR) NewStruct() *moderationConfigRoleR {
	return &moderationConfigRoleR{}
}

func (o *ModerationConfigRole) GetGuild() *ModerationConfig {
	if o == nil {
		return nil
	}

	return o.R.GetGuild()
}

func (r *moderationConfigRoleR) GetGuild() *ModerationConfig {
	if r == nil {
		return nil
	}

	return r.Guild
}

// moderationConfigRoleL is where Load methods for each relationship are stored.
type moderationConfigRoleL struct{}

var (
	moderationConfigRoleAllColumns            = []string{"guild_id", "action_type", "role_id"}
	moderationConfigRoleColumnsWithoutDefault = []string{"guild_id", "action_type", "role_id"}
	moderationConfigRoleColumnsWithDefault    = []string{}
	moderationConfigRolePrimaryKeyColumns     = []string{"action_type", "role_id"}
	moderationConfigRoleGeneratedColumns      = []string{}
)

type (
	// ModerationConfigRoleSlice is an alias for a slice of pointers to ModerationConfigRole.
	// This should almost always be used instead of []ModerationConfigRole.
	ModerationConfigRoleSlice []*ModerationConfigRole

	moderationConfigRoleQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	moderationConfigRoleType                 = reflect.TypeOf(&ModerationConfigRole{})
	moderationConfigRoleMapping              = queries.MakeStructMapping(moderationConfigRoleType)
	moderationConfigRolePrimaryKeyMapping, _ = queries.BindMapping(moderationConfigRoleType, moderationConfigRoleMapping, moderationConfigRolePrimaryKeyColumns)
	moderationConfigRoleInsertCacheMut       sync.RWMutex
	moderationConfigRoleInsertCache          = make(map[string]insertCache)
	moderationConfigRoleUpdateCacheMut       sync.RWMutex
	moderationConfigRoleUpdateCache          = make(map[string]updateCache)
	moderationConfigRoleUpsertCacheMut       sync.RWMutex
	moderationConfigRoleUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single moderationConfigRole record from the query using the global executor.
func (q moderationConfigRoleQuery) OneG(ctx context.Context) (*ModerationConfigRole, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single moderationConfigRole record from the query.
func (q moderationConfigRoleQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ModerationConfigRole, error) {
	o := &ModerationConfigRole{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for moderation_config_roles")
	}

	return o, nil
}

// AllG returns all ModerationConfigRole records from the query using the global executor.
func (q moderationConfigRoleQuery) AllG(ctx context.Context) (ModerationConfigRoleSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ModerationConfigRole records from the query.
func (q moderationConfigRoleQuery) All(ctx context.Context, exec boil.ContextExecutor) (ModerationConfigRoleSlice, error) {
	var o []*ModerationConfigRole

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ModerationConfigRole slice")
	}

	return o, nil
}

// CountG returns the count of all ModerationConfigRole records in the query using the global executor
func (q moderationConfigRoleQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ModerationConfigRole records in the query.
func (q moderationConfigRoleQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count moderation_config_roles rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q moderationConfigRoleQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q moderationConfigRoleQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if moderation_config_roles exists")
	}

	return count > 0, nil
}

// Guild pointed to by the foreign key.
func (o *ModerationConfigRole) Guild(mods ...qm.QueryMod) moderationConfigQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"guild_id\" = ?", o.GuildID),
	}

	queryMods = append(queryMods, mods...)

	return ModerationConfigs(queryMods...)
}

// LoadGuild allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (moderationConfigRoleL) LoadGuild(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModerationConfigRole interface{}, mods queries.Applicator) error {
	var slice []*ModerationConfigRole
	var object *ModerationConfigRole

	if singular {
		var ok bool
		object, ok = maybeModerationConfigRole.(*ModerationConfigRole)
		if !ok {
			object = new(ModerationConfigRole)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModerationConfigRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModerationConfigRole))
			}
		}
	} else {
		s, ok := maybeModerationConfigRole.(*[]*ModerationConfigRole)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModerationConfigRole)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModerationConfigRole))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &moderationConfigRoleR{}
		}
		args[object.GuildID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moderationConfigRoleR{}
			}

			args[obj.GuildID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`moderation_config`),
		qm.WhereIn(`moderation_config.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ModerationConfig")
	}

	var resultSlice []*ModerationConfig
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ModerationConfig")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for moderation_config")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for moderation_config")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Guild = foreign
		if foreign.R == nil {
			foreign.R = &moderationConfigR{}
		}
		foreign.R.GuildModerationConfigRoles = append(foreign.R.GuildModerationConfigRoles, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GuildID == foreign.GuildID {
				local.R.Guild = foreign
				if foreign.R == nil {
					foreign.R = &moderationConfigR{}
				}
				foreign.R.GuildModerationConfigRoles = append(foreign.R.GuildModerationConfigRoles, local)
				break
			}
		}
	}

	return nil
}

// SetGuildG of the moderationConfigRole to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildModerationConfigRoles.
// Uses the global database handle.
func (o *ModerationConfigRole) SetGuildG(ctx context.Context, insert bool, related *ModerationConfig) error {
	return o.SetGuild(ctx, boil.GetContextDB(), insert, related)
}

// SetGuild of the moderationConfigRole to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildModerationConfigRoles.
func (o *ModerationConfigRole) SetGuild(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ModerationConfig) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"moderation_config_roles\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
		strmangle.WhereClause("\"", "\"", 2, moderationConfigRolePrimaryKeyColumns),
	)
	values := []interface{}{related.GuildID, o.ActionType, o.RoleID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GuildID = related.GuildID
	if o.R == nil {
		o.R = &moderationConfigRoleR{
			Guild: related,
		}
	} else {
		o.R.Guild = related
	}

	if related.R == nil {
		related.R = &moderationConfigR{
			GuildModerationConfigRoles: ModerationConfigRoleSlice{o},
		}
	} else {
		related.R.GuildModerationConfigRoles = append(related.R.GuildModerationConfigRoles, o)
	}

	return nil
}

// ModerationConfigRoles retrieves all the records using an executor.
func ModerationConfigRoles(mods ...qm.QueryMod) moderationConfigRoleQuery {
	mods = append(mods, qm.From("\"moderation_config_roles\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"moderation_config_roles\".*"})
	}

	return moderationConfigRoleQuery{q}
}

// FindModerationConfigRoleG retrieves a single record by ID.
func FindModerationConfigRoleG(ctx context.Context, actionType string, roleID string, selectCols ...string) (*ModerationConfigRole, error) {
	return FindModerationConfigRole(ctx, boil.GetContextDB(), actionType, roleID, selectCols...)
}

// FindModerationConfigRole retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindModerationConfigRole(ctx context.Context, exec boil.ContextExecutor, actionType string, roleID string, selectCols ...string) (*ModerationConfigRole, error) {
	moderationConfigRoleObj := &ModerationConfigRole{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"moderation_config_roles\" where \"action_type\"=$1 AND \"role_id\"=$2", sel,
	)

	q := queries.Raw(query, actionType, roleID)

	err := q.Bind(ctx, exec, moderationConfigRoleObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from moderation_config_roles")
	}

	return moderationConfigRoleObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ModerationConfigRole) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ModerationConfigRole) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no moderation_config_roles provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(moderationConfigRoleColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	moderationConfigRoleInsertCacheMut.RLock()
	cache, cached := moderationConfigRoleInsertCache[key]
	moderationConfigRoleInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			moderationConfigRoleAllColumns,
			moderationConfigRoleColumnsWithDefault,
			moderationConfigRoleColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(moderationConfigRoleType, moderationConfigRoleMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(moderationConfigRoleType, moderationConfigRoleMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"moderation_config_roles\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"moderation_config_roles\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into moderation_config_roles")
	}

	if !cached {
		moderationConfigRoleInsertCacheMut.Lock()
		moderationConfigRoleInsertCache[key] = cache
		moderationConfigRoleInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single ModerationConfigRole record using the global executor.
// See Update for more documentation.
func (o *ModerationConfigRole) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ModerationConfigRole.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ModerationConfigRole) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	moderationConfigRoleUpdateCacheMut.RLock()
	cache, cached := moderationConfigRoleUpdateCache[key]
	moderationConfigRoleUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			moderationConfigRoleAllColumns,
			moderationConfigRolePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update moderation_config_roles, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"moderation_config_roles\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, moderationConfigRolePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(moderationConfigRoleType, moderationConfigRoleMapping, append(wl, moderationConfigRolePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update moderation_config_roles row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for moderation_config_roles")
	}

	if !cached {
		moderationConfigRoleUpdateCacheMut.Lock()
		moderationConfigRoleUpdateCache[key] = cache
		moderationConfigRoleUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q moderationConfigRoleQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q moderationConfigRoleQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for moderation_config_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for moderation_config_roles")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ModerationConfigRoleSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ModerationConfigRoleSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationConfigRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"moderation_config_roles\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, moderationConfigRolePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in moderationConfigRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all moderationConfigRole")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ModerationConfigRole) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ModerationConfigRole) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no moderation_config_roles provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(moderationConfigRoleColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	moderationConfigRoleUpsertCacheMut.RLock()
	cache, cached := moderationConfigRoleUpsertCache[key]
	moderationConfigRoleUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			moderationConfigRoleAllColumns,
			moderationConfigRoleColumnsWithDefault,
			moderationConfigRoleColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			moderationConfigRoleAllColumns,
			moderationConfigRolePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert moderation_config_roles, could not build update column list")
		}

		ret := strmangle.SetComplement(moderationConfigRoleAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(moderationConfigRolePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert moderation_config_roles, could not build conflict column list")
			}

			conflict = make([]string, len(moderationConfigRolePrimaryKeyColumns))
			copy(conflict, moderationConfigRolePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"moderation_config_roles\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(moderationConfigRoleType, moderationConfigRoleMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(moderationConfigRoleType, moderationConfigRoleMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert moderation_config_roles")
	}

	if !cached {
		moderationConfigRoleUpsertCacheMut.Lock()
		moderationConfigRoleUpsertCache[key] = cache
		moderationConfigRoleUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single ModerationConfigRole record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ModerationConfigRole) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ModerationConfigRole record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ModerationConfigRole) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ModerationConfigRole provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), moderationConfigRolePrimaryKeyMapping)
	sql := "DELETE FROM \"moderation_config_roles\" WHERE \"action_type\"=$1 AND \"role_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from moderation_config_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for moderation_config_roles")
	}

	return rowsAff, nil
}

func (q moderationConfigRoleQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q moderationConfigRoleQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no moderationConfigRoleQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderation_config_roles")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_config_roles")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ModerationConfigRoleSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ModerationConfigRoleSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationConfigRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"moderation_config_roles\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationConfigRolePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderationConfigRole slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_config_roles")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ModerationConfigRole) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no ModerationConfigRole provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ModerationConfigRole) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindModerationConfigRole(ctx, exec, o.ActionType, o.RoleID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationConfigRoleSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty ModerationConfigRoleSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationConfigRoleSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ModerationConfigRoleSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationConfigRolePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"moderation_config_roles\".* FROM \"moderation_config_roles\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationConfigRolePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ModerationConfigRoleSlice")
	}

	*o = slice

	return nil
}

// ModerationConfigRoleExistsG checks if the ModerationConfigRole row exists.
func ModerationConfigRoleExistsG(ctx context.Context, actionType string, roleID string) (bool, error) {
	return ModerationConfigRoleExists(ctx, boil.GetContextDB(), actionType, roleID)
}

// ModerationConfigRoleExists checks if the ModerationConfigRole row exists.
func ModerationConfigRoleExists(ctx context.Context, exec boil.ContextExecutor, actionType string, roleID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"moderation_config_roles\" where \"action_type\"=$1 AND \"role_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, actionType, roleID)
	}
	row := exec.QueryRowContext(ctx, sql, actionType, roleID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if moderation_config_roles exists")
	}

	return exists, nil
}

// Exists checks if the ModerationConfigRole row exists.
func (o *ModerationConfigRole) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ModerationConfigRoleExists(ctx, exec, o.ActionType, o.RoleID)
}
