#!/bin/bash

## Bot 
# Your Discord bot token
export SUMMIT_TOKEN="tokenXXXX"
# Your Discord bot client ID
export SUMMIT_CLIENTID="clientIDXXXX"
# Your Discord bot client secret
export SUMMIT_CLIENTSECRET="secretXXXX"
# Your user ID (to access bot admin commands)
export SUMMIT_OWNERID="userIDXXXX"

## GitHub (to load latest releases on dashboard)
# Your GitHub username
export SUMMIT_GITHUBREPOOWNER="userNameXXXX"
# Your Summit GitHub repo
export SUMMIT_GITHUBREPO="repoNameXXXX"

## Database
# The host address of the PostgreSQL database
export SUMMIT_PGHOST="localhost"
# The name of the PostgreSQL database
export SUMMIT_PGDB="SUMMIT"
# The PostgreSQL username for connecting
export SUMMIT_PGUSER="SUMMIT"
# The password for the PostgreSQL account for connecting
export SUMMIT_PGPASSWORD="password"

## Dashboard
# The domain name or IP address where the bot dashboard is hosted
export SUMMIT_HOST="your_domain_here"
# An optional override for the terms page link
export SUMMIT_TERMSURLOVERRIDE="your_full_URL_here" # optional
# An optional override for the privacy page link
export SUMMIT_PRIVACYURLOVERRIDE="your_full_URL_here" # optional

