// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BannedGuilds string
	CoreConfig   string
}{
	BannedGuilds: "banned_guilds",
	CoreConfig:   "core_config",
}
