name: asbwig

volumes:
  db:

networks:
  default:

services:
  app:
    container_name: asbwig-dev-app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - default
    env_file:
      - app.dev.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8085:8085
  db:
    container_name: asbwig-dev-postgres-db
    image: postgres:16
    restart: no
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.dev.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5