// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	EconomyConfig          string
	EconomyCooldowns       string
	EconomyCreateitem      string
	EconomyCustomResponses string
	EconomyShop            string
	EconomyUserInventories string
	EconomyUsers           string
}{
	EconomyConfig:          "economy_config",
	EconomyCooldowns:       "economy_cooldowns",
	EconomyCreateitem:      "economy_createitem",
	EconomyCustomResponses: "economy_custom_responses",
	EconomyShop:            "economy_shop",
	EconomyUserInventories: "economy_user_inventories",
	EconomyUsers:           "economy_users",
}
