// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	EconomyBank      string
	EconomyCash      string
	EconomyConfig    string
	EconomyCooldowns string
	EconomyShop      string
}{
	EconomyBank:      "economy_bank",
	EconomyCash:      "economy_cash",
	EconomyConfig:    "economy_config",
	EconomyCooldowns: "economy_cooldowns",
	EconomyShop:      "economy_shop",
}
