// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EconomyCooldown is an object representing the database table.
type EconomyCooldown struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	GuildID   string    `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	UserID    string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Type      string    `boil:"type" json:"type" toml:"type" yaml:"type"`
	ExpiresAt null.Time `boil:"expires_at" json:"expires_at,omitempty" toml:"expires_at" yaml:"expires_at,omitempty"`

	R *economyCooldownR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L economyCooldownL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EconomyCooldownColumns = struct {
	ID        string
	GuildID   string
	UserID    string
	Type      string
	ExpiresAt string
}{
	ID:        "id",
	GuildID:   "guild_id",
	UserID:    "user_id",
	Type:      "type",
	ExpiresAt: "expires_at",
}

var EconomyCooldownTableColumns = struct {
	ID        string
	GuildID   string
	UserID    string
	Type      string
	ExpiresAt string
}{
	ID:        "economy_cooldowns.id",
	GuildID:   "economy_cooldowns.guild_id",
	UserID:    "economy_cooldowns.user_id",
	Type:      "economy_cooldowns.type",
	ExpiresAt: "economy_cooldowns.expires_at",
}

// Generated where

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var EconomyCooldownWhere = struct {
	ID        whereHelperint
	GuildID   whereHelperstring
	UserID    whereHelperstring
	Type      whereHelperstring
	ExpiresAt whereHelpernull_Time
}{
	ID:        whereHelperint{field: "\"economy_cooldowns\".\"id\""},
	GuildID:   whereHelperstring{field: "\"economy_cooldowns\".\"guild_id\""},
	UserID:    whereHelperstring{field: "\"economy_cooldowns\".\"user_id\""},
	Type:      whereHelperstring{field: "\"economy_cooldowns\".\"type\""},
	ExpiresAt: whereHelpernull_Time{field: "\"economy_cooldowns\".\"expires_at\""},
}

// EconomyCooldownRels is where relationship names are stored.
var EconomyCooldownRels = struct {
}{}

// economyCooldownR is where relationships are stored.
type economyCooldownR struct {
}

// NewStruct creates a new relationship struct
func (*economyCooldownR) NewStruct() *economyCooldownR {
	return &economyCooldownR{}
}

// economyCooldownL is where Load methods for each relationship are stored.
type economyCooldownL struct{}

var (
	economyCooldownAllColumns            = []string{"id", "guild_id", "user_id", "type", "expires_at"}
	economyCooldownColumnsWithoutDefault = []string{"guild_id", "user_id", "type"}
	economyCooldownColumnsWithDefault    = []string{"id", "expires_at"}
	economyCooldownPrimaryKeyColumns     = []string{"id"}
	economyCooldownGeneratedColumns      = []string{}
)

type (
	// EconomyCooldownSlice is an alias for a slice of pointers to EconomyCooldown.
	// This should almost always be used instead of []EconomyCooldown.
	EconomyCooldownSlice []*EconomyCooldown

	economyCooldownQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	economyCooldownType                 = reflect.TypeOf(&EconomyCooldown{})
	economyCooldownMapping              = queries.MakeStructMapping(economyCooldownType)
	economyCooldownPrimaryKeyMapping, _ = queries.BindMapping(economyCooldownType, economyCooldownMapping, economyCooldownPrimaryKeyColumns)
	economyCooldownInsertCacheMut       sync.RWMutex
	economyCooldownInsertCache          = make(map[string]insertCache)
	economyCooldownUpdateCacheMut       sync.RWMutex
	economyCooldownUpdateCache          = make(map[string]updateCache)
	economyCooldownUpsertCacheMut       sync.RWMutex
	economyCooldownUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single economyCooldown record from the query using the global executor.
func (q economyCooldownQuery) OneG(ctx context.Context) (*EconomyCooldown, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single economyCooldown record from the query.
func (q economyCooldownQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EconomyCooldown, error) {
	o := &EconomyCooldown{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for economy_cooldowns")
	}

	return o, nil
}

// AllG returns all EconomyCooldown records from the query using the global executor.
func (q economyCooldownQuery) AllG(ctx context.Context) (EconomyCooldownSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all EconomyCooldown records from the query.
func (q economyCooldownQuery) All(ctx context.Context, exec boil.ContextExecutor) (EconomyCooldownSlice, error) {
	var o []*EconomyCooldown

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EconomyCooldown slice")
	}

	return o, nil
}

// CountG returns the count of all EconomyCooldown records in the query using the global executor
func (q economyCooldownQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all EconomyCooldown records in the query.
func (q economyCooldownQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count economy_cooldowns rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q economyCooldownQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q economyCooldownQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if economy_cooldowns exists")
	}

	return count > 0, nil
}

// EconomyCooldowns retrieves all the records using an executor.
func EconomyCooldowns(mods ...qm.QueryMod) economyCooldownQuery {
	mods = append(mods, qm.From("\"economy_cooldowns\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"economy_cooldowns\".*"})
	}

	return economyCooldownQuery{q}
}

// FindEconomyCooldownG retrieves a single record by ID.
func FindEconomyCooldownG(ctx context.Context, iD int, selectCols ...string) (*EconomyCooldown, error) {
	return FindEconomyCooldown(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindEconomyCooldown retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEconomyCooldown(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*EconomyCooldown, error) {
	economyCooldownObj := &EconomyCooldown{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"economy_cooldowns\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, economyCooldownObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from economy_cooldowns")
	}

	return economyCooldownObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *EconomyCooldown) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EconomyCooldown) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_cooldowns provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(economyCooldownColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	economyCooldownInsertCacheMut.RLock()
	cache, cached := economyCooldownInsertCache[key]
	economyCooldownInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			economyCooldownAllColumns,
			economyCooldownColumnsWithDefault,
			economyCooldownColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(economyCooldownType, economyCooldownMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(economyCooldownType, economyCooldownMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"economy_cooldowns\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"economy_cooldowns\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into economy_cooldowns")
	}

	if !cached {
		economyCooldownInsertCacheMut.Lock()
		economyCooldownInsertCache[key] = cache
		economyCooldownInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single EconomyCooldown record using the global executor.
// See Update for more documentation.
func (o *EconomyCooldown) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the EconomyCooldown.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EconomyCooldown) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	economyCooldownUpdateCacheMut.RLock()
	cache, cached := economyCooldownUpdateCache[key]
	economyCooldownUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			economyCooldownAllColumns,
			economyCooldownPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update economy_cooldowns, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"economy_cooldowns\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, economyCooldownPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(economyCooldownType, economyCooldownMapping, append(wl, economyCooldownPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update economy_cooldowns row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for economy_cooldowns")
	}

	if !cached {
		economyCooldownUpdateCacheMut.Lock()
		economyCooldownUpdateCache[key] = cache
		economyCooldownUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q economyCooldownQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q economyCooldownQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for economy_cooldowns")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for economy_cooldowns")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o EconomyCooldownSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EconomyCooldownSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyCooldownPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"economy_cooldowns\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, economyCooldownPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in economyCooldown slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all economyCooldown")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *EconomyCooldown) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EconomyCooldown) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no economy_cooldowns provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(economyCooldownColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	economyCooldownUpsertCacheMut.RLock()
	cache, cached := economyCooldownUpsertCache[key]
	economyCooldownUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			economyCooldownAllColumns,
			economyCooldownColumnsWithDefault,
			economyCooldownColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			economyCooldownAllColumns,
			economyCooldownPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert economy_cooldowns, could not build update column list")
		}

		ret := strmangle.SetComplement(economyCooldownAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(economyCooldownPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert economy_cooldowns, could not build conflict column list")
			}

			conflict = make([]string, len(economyCooldownPrimaryKeyColumns))
			copy(conflict, economyCooldownPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"economy_cooldowns\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(economyCooldownType, economyCooldownMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(economyCooldownType, economyCooldownMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert economy_cooldowns")
	}

	if !cached {
		economyCooldownUpsertCacheMut.Lock()
		economyCooldownUpsertCache[key] = cache
		economyCooldownUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single EconomyCooldown record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *EconomyCooldown) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single EconomyCooldown record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EconomyCooldown) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EconomyCooldown provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), economyCooldownPrimaryKeyMapping)
	sql := "DELETE FROM \"economy_cooldowns\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from economy_cooldowns")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for economy_cooldowns")
	}

	return rowsAff, nil
}

func (q economyCooldownQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q economyCooldownQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no economyCooldownQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economy_cooldowns")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_cooldowns")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o EconomyCooldownSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EconomyCooldownSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyCooldownPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"economy_cooldowns\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyCooldownPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economyCooldown slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_cooldowns")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *EconomyCooldown) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no EconomyCooldown provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EconomyCooldown) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEconomyCooldown(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyCooldownSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty EconomyCooldownSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyCooldownSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EconomyCooldownSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyCooldownPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"economy_cooldowns\".* FROM \"economy_cooldowns\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyCooldownPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EconomyCooldownSlice")
	}

	*o = slice

	return nil
}

// EconomyCooldownExistsG checks if the EconomyCooldown row exists.
func EconomyCooldownExistsG(ctx context.Context, iD int) (bool, error) {
	return EconomyCooldownExists(ctx, boil.GetContextDB(), iD)
}

// EconomyCooldownExists checks if the EconomyCooldown row exists.
func EconomyCooldownExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"economy_cooldowns\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if economy_cooldowns exists")
	}

	return exists, nil
}

// Exists checks if the EconomyCooldown row exists.
func (o *EconomyCooldown) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EconomyCooldownExists(ctx, exec, o.ID)
}
