// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EconomyUserInventory is an object representing the database table.
type EconomyUserInventory struct {
	GuildID     string `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	UserID      string `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Name        string `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description string `boil:"description" json:"description" toml:"description" yaml:"description"`
	Quantity    int64  `boil:"quantity" json:"quantity" toml:"quantity" yaml:"quantity"`
	Role        string `boil:"role" json:"role" toml:"role" yaml:"role"`
	Reply       string `boil:"reply" json:"reply" toml:"reply" yaml:"reply"`

	R *economyUserInventoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L economyUserInventoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EconomyUserInventoryColumns = struct {
	GuildID     string
	UserID      string
	Name        string
	Description string
	Quantity    string
	Role        string
	Reply       string
}{
	GuildID:     "guild_id",
	UserID:      "user_id",
	Name:        "name",
	Description: "description",
	Quantity:    "quantity",
	Role:        "role",
	Reply:       "reply",
}

var EconomyUserInventoryTableColumns = struct {
	GuildID     string
	UserID      string
	Name        string
	Description string
	Quantity    string
	Role        string
	Reply       string
}{
	GuildID:     "economy_user_inventories.guild_id",
	UserID:      "economy_user_inventories.user_id",
	Name:        "economy_user_inventories.name",
	Description: "economy_user_inventories.description",
	Quantity:    "economy_user_inventories.quantity",
	Role:        "economy_user_inventories.role",
	Reply:       "economy_user_inventories.reply",
}

// Generated where

var EconomyUserInventoryWhere = struct {
	GuildID     whereHelperstring
	UserID      whereHelperstring
	Name        whereHelperstring
	Description whereHelperstring
	Quantity    whereHelperint64
	Role        whereHelperstring
	Reply       whereHelperstring
}{
	GuildID:     whereHelperstring{field: "\"economy_user_inventories\".\"guild_id\""},
	UserID:      whereHelperstring{field: "\"economy_user_inventories\".\"user_id\""},
	Name:        whereHelperstring{field: "\"economy_user_inventories\".\"name\""},
	Description: whereHelperstring{field: "\"economy_user_inventories\".\"description\""},
	Quantity:    whereHelperint64{field: "\"economy_user_inventories\".\"quantity\""},
	Role:        whereHelperstring{field: "\"economy_user_inventories\".\"role\""},
	Reply:       whereHelperstring{field: "\"economy_user_inventories\".\"reply\""},
}

// EconomyUserInventoryRels is where relationship names are stored.
var EconomyUserInventoryRels = struct {
	Guild string
}{
	Guild: "Guild",
}

// economyUserInventoryR is where relationships are stored.
type economyUserInventoryR struct {
	Guild *EconomyConfig `boil:"Guild" json:"Guild" toml:"Guild" yaml:"Guild"`
}

// NewStruct creates a new relationship struct
func (*economyUserInventoryR) NewStruct() *economyUserInventoryR {
	return &economyUserInventoryR{}
}

func (r *economyUserInventoryR) GetGuild() *EconomyConfig {
	if r == nil {
		return nil
	}
	return r.Guild
}

// economyUserInventoryL is where Load methods for each relationship are stored.
type economyUserInventoryL struct{}

var (
	economyUserInventoryAllColumns            = []string{"guild_id", "user_id", "name", "description", "quantity", "role", "reply"}
	economyUserInventoryColumnsWithoutDefault = []string{"guild_id", "user_id", "name", "description", "quantity", "role", "reply"}
	economyUserInventoryColumnsWithDefault    = []string{}
	economyUserInventoryPrimaryKeyColumns     = []string{"guild_id", "user_id", "name"}
	economyUserInventoryGeneratedColumns      = []string{}
)

type (
	// EconomyUserInventorySlice is an alias for a slice of pointers to EconomyUserInventory.
	// This should almost always be used instead of []EconomyUserInventory.
	EconomyUserInventorySlice []*EconomyUserInventory

	economyUserInventoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	economyUserInventoryType                 = reflect.TypeOf(&EconomyUserInventory{})
	economyUserInventoryMapping              = queries.MakeStructMapping(economyUserInventoryType)
	economyUserInventoryPrimaryKeyMapping, _ = queries.BindMapping(economyUserInventoryType, economyUserInventoryMapping, economyUserInventoryPrimaryKeyColumns)
	economyUserInventoryInsertCacheMut       sync.RWMutex
	economyUserInventoryInsertCache          = make(map[string]insertCache)
	economyUserInventoryUpdateCacheMut       sync.RWMutex
	economyUserInventoryUpdateCache          = make(map[string]updateCache)
	economyUserInventoryUpsertCacheMut       sync.RWMutex
	economyUserInventoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single economyUserInventory record from the query using the global executor.
func (q economyUserInventoryQuery) OneG(ctx context.Context) (*EconomyUserInventory, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single economyUserInventory record from the query.
func (q economyUserInventoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EconomyUserInventory, error) {
	o := &EconomyUserInventory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for economy_user_inventories")
	}

	return o, nil
}

// AllG returns all EconomyUserInventory records from the query using the global executor.
func (q economyUserInventoryQuery) AllG(ctx context.Context) (EconomyUserInventorySlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all EconomyUserInventory records from the query.
func (q economyUserInventoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (EconomyUserInventorySlice, error) {
	var o []*EconomyUserInventory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EconomyUserInventory slice")
	}

	return o, nil
}

// CountG returns the count of all EconomyUserInventory records in the query using the global executor
func (q economyUserInventoryQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all EconomyUserInventory records in the query.
func (q economyUserInventoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count economy_user_inventories rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q economyUserInventoryQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q economyUserInventoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if economy_user_inventories exists")
	}

	return count > 0, nil
}

// Guild pointed to by the foreign key.
func (o *EconomyUserInventory) Guild(mods ...qm.QueryMod) economyConfigQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"guild_id\" = ?", o.GuildID),
	}

	queryMods = append(queryMods, mods...)

	return EconomyConfigs(queryMods...)
}

// LoadGuild allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (economyUserInventoryL) LoadGuild(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEconomyUserInventory interface{}, mods queries.Applicator) error {
	var slice []*EconomyUserInventory
	var object *EconomyUserInventory

	if singular {
		var ok bool
		object, ok = maybeEconomyUserInventory.(*EconomyUserInventory)
		if !ok {
			object = new(EconomyUserInventory)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEconomyUserInventory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEconomyUserInventory))
			}
		}
	} else {
		s, ok := maybeEconomyUserInventory.(*[]*EconomyUserInventory)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEconomyUserInventory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEconomyUserInventory))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &economyUserInventoryR{}
		}
		args[object.GuildID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &economyUserInventoryR{}
			}

			args[obj.GuildID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`economy_config`),
		qm.WhereIn(`economy_config.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load EconomyConfig")
	}

	var resultSlice []*EconomyConfig
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice EconomyConfig")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for economy_config")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for economy_config")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Guild = foreign
		if foreign.R == nil {
			foreign.R = &economyConfigR{}
		}
		foreign.R.GuildEconomyUserInventories = append(foreign.R.GuildEconomyUserInventories, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GuildID == foreign.GuildID {
				local.R.Guild = foreign
				if foreign.R == nil {
					foreign.R = &economyConfigR{}
				}
				foreign.R.GuildEconomyUserInventories = append(foreign.R.GuildEconomyUserInventories, local)
				break
			}
		}
	}

	return nil
}

// SetGuildG of the economyUserInventory to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildEconomyUserInventories.
// Uses the global database handle.
func (o *EconomyUserInventory) SetGuildG(ctx context.Context, insert bool, related *EconomyConfig) error {
	return o.SetGuild(ctx, boil.GetContextDB(), insert, related)
}

// SetGuild of the economyUserInventory to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildEconomyUserInventories.
func (o *EconomyUserInventory) SetGuild(ctx context.Context, exec boil.ContextExecutor, insert bool, related *EconomyConfig) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"economy_user_inventories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
		strmangle.WhereClause("\"", "\"", 2, economyUserInventoryPrimaryKeyColumns),
	)
	values := []interface{}{related.GuildID, o.GuildID, o.UserID, o.Name}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GuildID = related.GuildID
	if o.R == nil {
		o.R = &economyUserInventoryR{
			Guild: related,
		}
	} else {
		o.R.Guild = related
	}

	if related.R == nil {
		related.R = &economyConfigR{
			GuildEconomyUserInventories: EconomyUserInventorySlice{o},
		}
	} else {
		related.R.GuildEconomyUserInventories = append(related.R.GuildEconomyUserInventories, o)
	}

	return nil
}

// EconomyUserInventories retrieves all the records using an executor.
func EconomyUserInventories(mods ...qm.QueryMod) economyUserInventoryQuery {
	mods = append(mods, qm.From("\"economy_user_inventories\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"economy_user_inventories\".*"})
	}

	return economyUserInventoryQuery{q}
}

// FindEconomyUserInventoryG retrieves a single record by ID.
func FindEconomyUserInventoryG(ctx context.Context, guildID string, userID string, name string, selectCols ...string) (*EconomyUserInventory, error) {
	return FindEconomyUserInventory(ctx, boil.GetContextDB(), guildID, userID, name, selectCols...)
}

// FindEconomyUserInventory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEconomyUserInventory(ctx context.Context, exec boil.ContextExecutor, guildID string, userID string, name string, selectCols ...string) (*EconomyUserInventory, error) {
	economyUserInventoryObj := &EconomyUserInventory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"economy_user_inventories\" where \"guild_id\"=$1 AND \"user_id\"=$2 AND \"name\"=$3", sel,
	)

	q := queries.Raw(query, guildID, userID, name)

	err := q.Bind(ctx, exec, economyUserInventoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from economy_user_inventories")
	}

	return economyUserInventoryObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *EconomyUserInventory) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EconomyUserInventory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_user_inventories provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(economyUserInventoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	economyUserInventoryInsertCacheMut.RLock()
	cache, cached := economyUserInventoryInsertCache[key]
	economyUserInventoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			economyUserInventoryAllColumns,
			economyUserInventoryColumnsWithDefault,
			economyUserInventoryColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(economyUserInventoryType, economyUserInventoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(economyUserInventoryType, economyUserInventoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"economy_user_inventories\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"economy_user_inventories\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into economy_user_inventories")
	}

	if !cached {
		economyUserInventoryInsertCacheMut.Lock()
		economyUserInventoryInsertCache[key] = cache
		economyUserInventoryInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single EconomyUserInventory record using the global executor.
// See Update for more documentation.
func (o *EconomyUserInventory) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the EconomyUserInventory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EconomyUserInventory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	economyUserInventoryUpdateCacheMut.RLock()
	cache, cached := economyUserInventoryUpdateCache[key]
	economyUserInventoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			economyUserInventoryAllColumns,
			economyUserInventoryPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update economy_user_inventories, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"economy_user_inventories\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, economyUserInventoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(economyUserInventoryType, economyUserInventoryMapping, append(wl, economyUserInventoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update economy_user_inventories row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for economy_user_inventories")
	}

	if !cached {
		economyUserInventoryUpdateCacheMut.Lock()
		economyUserInventoryUpdateCache[key] = cache
		economyUserInventoryUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q economyUserInventoryQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q economyUserInventoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for economy_user_inventories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for economy_user_inventories")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o EconomyUserInventorySlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EconomyUserInventorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyUserInventoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"economy_user_inventories\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, economyUserInventoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in economyUserInventory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all economyUserInventory")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *EconomyUserInventory) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EconomyUserInventory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no economy_user_inventories provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(economyUserInventoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	economyUserInventoryUpsertCacheMut.RLock()
	cache, cached := economyUserInventoryUpsertCache[key]
	economyUserInventoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			economyUserInventoryAllColumns,
			economyUserInventoryColumnsWithDefault,
			economyUserInventoryColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			economyUserInventoryAllColumns,
			economyUserInventoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert economy_user_inventories, could not build update column list")
		}

		ret := strmangle.SetComplement(economyUserInventoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(economyUserInventoryPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert economy_user_inventories, could not build conflict column list")
			}

			conflict = make([]string, len(economyUserInventoryPrimaryKeyColumns))
			copy(conflict, economyUserInventoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"economy_user_inventories\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(economyUserInventoryType, economyUserInventoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(economyUserInventoryType, economyUserInventoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert economy_user_inventories")
	}

	if !cached {
		economyUserInventoryUpsertCacheMut.Lock()
		economyUserInventoryUpsertCache[key] = cache
		economyUserInventoryUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single EconomyUserInventory record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *EconomyUserInventory) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single EconomyUserInventory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EconomyUserInventory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EconomyUserInventory provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), economyUserInventoryPrimaryKeyMapping)
	sql := "DELETE FROM \"economy_user_inventories\" WHERE \"guild_id\"=$1 AND \"user_id\"=$2 AND \"name\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from economy_user_inventories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for economy_user_inventories")
	}

	return rowsAff, nil
}

func (q economyUserInventoryQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q economyUserInventoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no economyUserInventoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economy_user_inventories")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_user_inventories")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o EconomyUserInventorySlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EconomyUserInventorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyUserInventoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"economy_user_inventories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyUserInventoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economyUserInventory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_user_inventories")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *EconomyUserInventory) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no EconomyUserInventory provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EconomyUserInventory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEconomyUserInventory(ctx, exec, o.GuildID, o.UserID, o.Name)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyUserInventorySlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty EconomyUserInventorySlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyUserInventorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EconomyUserInventorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyUserInventoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"economy_user_inventories\".* FROM \"economy_user_inventories\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyUserInventoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EconomyUserInventorySlice")
	}

	*o = slice

	return nil
}

// EconomyUserInventoryExistsG checks if the EconomyUserInventory row exists.
func EconomyUserInventoryExistsG(ctx context.Context, guildID string, userID string, name string) (bool, error) {
	return EconomyUserInventoryExists(ctx, boil.GetContextDB(), guildID, userID, name)
}

// EconomyUserInventoryExists checks if the EconomyUserInventory row exists.
func EconomyUserInventoryExists(ctx context.Context, exec boil.ContextExecutor, guildID string, userID string, name string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"economy_user_inventories\" where \"guild_id\"=$1 AND \"user_id\"=$2 AND \"name\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID, userID, name)
	}
	row := exec.QueryRowContext(ctx, sql, guildID, userID, name)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if economy_user_inventories exists")
	}

	return exists, nil
}

// Exists checks if the EconomyUserInventory row exists.
func (o *EconomyUserInventory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EconomyUserInventoryExists(ctx, exec, o.GuildID, o.UserID, o.Name)
}
