// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EconomyShop is an object representing the database table.
type EconomyShop struct {
	GuildID     string `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	Name        string `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description string `boil:"description" json:"description" toml:"description" yaml:"description"`
	Price       int64  `boil:"price" json:"price" toml:"price" yaml:"price"`
	Quantity    int64  `boil:"quantity" json:"quantity" toml:"quantity" yaml:"quantity"`
	Role        string `boil:"role" json:"role" toml:"role" yaml:"role"`
	Reply       string `boil:"reply" json:"reply" toml:"reply" yaml:"reply"`
	Soldby      string `boil:"soldby" json:"soldby" toml:"soldby" yaml:"soldby"`

	R *economyShopR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L economyShopL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EconomyShopColumns = struct {
	GuildID     string
	Name        string
	Description string
	Price       string
	Quantity    string
	Role        string
	Reply       string
	Soldby      string
}{
	GuildID:     "guild_id",
	Name:        "name",
	Description: "description",
	Price:       "price",
	Quantity:    "quantity",
	Role:        "role",
	Reply:       "reply",
	Soldby:      "soldby",
}

var EconomyShopTableColumns = struct {
	GuildID     string
	Name        string
	Description string
	Price       string
	Quantity    string
	Role        string
	Reply       string
	Soldby      string
}{
	GuildID:     "economy_shop.guild_id",
	Name:        "economy_shop.name",
	Description: "economy_shop.description",
	Price:       "economy_shop.price",
	Quantity:    "economy_shop.quantity",
	Role:        "economy_shop.role",
	Reply:       "economy_shop.reply",
	Soldby:      "economy_shop.soldby",
}

// Generated where

var EconomyShopWhere = struct {
	GuildID     whereHelperstring
	Name        whereHelperstring
	Description whereHelperstring
	Price       whereHelperint64
	Quantity    whereHelperint64
	Role        whereHelperstring
	Reply       whereHelperstring
	Soldby      whereHelperstring
}{
	GuildID:     whereHelperstring{field: "\"economy_shop\".\"guild_id\""},
	Name:        whereHelperstring{field: "\"economy_shop\".\"name\""},
	Description: whereHelperstring{field: "\"economy_shop\".\"description\""},
	Price:       whereHelperint64{field: "\"economy_shop\".\"price\""},
	Quantity:    whereHelperint64{field: "\"economy_shop\".\"quantity\""},
	Role:        whereHelperstring{field: "\"economy_shop\".\"role\""},
	Reply:       whereHelperstring{field: "\"economy_shop\".\"reply\""},
	Soldby:      whereHelperstring{field: "\"economy_shop\".\"soldby\""},
}

// EconomyShopRels is where relationship names are stored.
var EconomyShopRels = struct {
	Guild string
}{
	Guild: "Guild",
}

// economyShopR is where relationships are stored.
type economyShopR struct {
	Guild *EconomyConfig `boil:"Guild" json:"Guild" toml:"Guild" yaml:"Guild"`
}

// NewStruct creates a new relationship struct
func (*economyShopR) NewStruct() *economyShopR {
	return &economyShopR{}
}

func (r *economyShopR) GetGuild() *EconomyConfig {
	if r == nil {
		return nil
	}
	return r.Guild
}

// economyShopL is where Load methods for each relationship are stored.
type economyShopL struct{}

var (
	economyShopAllColumns            = []string{"guild_id", "name", "description", "price", "quantity", "role", "reply", "soldby"}
	economyShopColumnsWithoutDefault = []string{"guild_id", "name", "description", "price", "quantity", "role", "reply", "soldby"}
	economyShopColumnsWithDefault    = []string{}
	economyShopPrimaryKeyColumns     = []string{"guild_id", "name", "soldby"}
	economyShopGeneratedColumns      = []string{}
)

type (
	// EconomyShopSlice is an alias for a slice of pointers to EconomyShop.
	// This should almost always be used instead of []EconomyShop.
	EconomyShopSlice []*EconomyShop

	economyShopQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	economyShopType                 = reflect.TypeOf(&EconomyShop{})
	economyShopMapping              = queries.MakeStructMapping(economyShopType)
	economyShopPrimaryKeyMapping, _ = queries.BindMapping(economyShopType, economyShopMapping, economyShopPrimaryKeyColumns)
	economyShopInsertCacheMut       sync.RWMutex
	economyShopInsertCache          = make(map[string]insertCache)
	economyShopUpdateCacheMut       sync.RWMutex
	economyShopUpdateCache          = make(map[string]updateCache)
	economyShopUpsertCacheMut       sync.RWMutex
	economyShopUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single economyShop record from the query using the global executor.
func (q economyShopQuery) OneG(ctx context.Context) (*EconomyShop, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single economyShop record from the query.
func (q economyShopQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EconomyShop, error) {
	o := &EconomyShop{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for economy_shop")
	}

	return o, nil
}

// AllG returns all EconomyShop records from the query using the global executor.
func (q economyShopQuery) AllG(ctx context.Context) (EconomyShopSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all EconomyShop records from the query.
func (q economyShopQuery) All(ctx context.Context, exec boil.ContextExecutor) (EconomyShopSlice, error) {
	var o []*EconomyShop

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EconomyShop slice")
	}

	return o, nil
}

// CountG returns the count of all EconomyShop records in the query using the global executor
func (q economyShopQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all EconomyShop records in the query.
func (q economyShopQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count economy_shop rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q economyShopQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q economyShopQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if economy_shop exists")
	}

	return count > 0, nil
}

// Guild pointed to by the foreign key.
func (o *EconomyShop) Guild(mods ...qm.QueryMod) economyConfigQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"guild_id\" = ?", o.GuildID),
	}

	queryMods = append(queryMods, mods...)

	return EconomyConfigs(queryMods...)
}

// LoadGuild allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (economyShopL) LoadGuild(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEconomyShop interface{}, mods queries.Applicator) error {
	var slice []*EconomyShop
	var object *EconomyShop

	if singular {
		var ok bool
		object, ok = maybeEconomyShop.(*EconomyShop)
		if !ok {
			object = new(EconomyShop)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEconomyShop)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEconomyShop))
			}
		}
	} else {
		s, ok := maybeEconomyShop.(*[]*EconomyShop)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEconomyShop)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEconomyShop))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &economyShopR{}
		}
		args[object.GuildID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &economyShopR{}
			}

			args[obj.GuildID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`economy_config`),
		qm.WhereIn(`economy_config.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load EconomyConfig")
	}

	var resultSlice []*EconomyConfig
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice EconomyConfig")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for economy_config")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for economy_config")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Guild = foreign
		if foreign.R == nil {
			foreign.R = &economyConfigR{}
		}
		foreign.R.GuildEconomyShops = append(foreign.R.GuildEconomyShops, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GuildID == foreign.GuildID {
				local.R.Guild = foreign
				if foreign.R == nil {
					foreign.R = &economyConfigR{}
				}
				foreign.R.GuildEconomyShops = append(foreign.R.GuildEconomyShops, local)
				break
			}
		}
	}

	return nil
}

// SetGuildG of the economyShop to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildEconomyShops.
// Uses the global database handle.
func (o *EconomyShop) SetGuildG(ctx context.Context, insert bool, related *EconomyConfig) error {
	return o.SetGuild(ctx, boil.GetContextDB(), insert, related)
}

// SetGuild of the economyShop to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildEconomyShops.
func (o *EconomyShop) SetGuild(ctx context.Context, exec boil.ContextExecutor, insert bool, related *EconomyConfig) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"economy_shop\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
		strmangle.WhereClause("\"", "\"", 2, economyShopPrimaryKeyColumns),
	)
	values := []interface{}{related.GuildID, o.GuildID, o.Name, o.Soldby}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GuildID = related.GuildID
	if o.R == nil {
		o.R = &economyShopR{
			Guild: related,
		}
	} else {
		o.R.Guild = related
	}

	if related.R == nil {
		related.R = &economyConfigR{
			GuildEconomyShops: EconomyShopSlice{o},
		}
	} else {
		related.R.GuildEconomyShops = append(related.R.GuildEconomyShops, o)
	}

	return nil
}

// EconomyShops retrieves all the records using an executor.
func EconomyShops(mods ...qm.QueryMod) economyShopQuery {
	mods = append(mods, qm.From("\"economy_shop\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"economy_shop\".*"})
	}

	return economyShopQuery{q}
}

// FindEconomyShopG retrieves a single record by ID.
func FindEconomyShopG(ctx context.Context, guildID string, name string, soldby string, selectCols ...string) (*EconomyShop, error) {
	return FindEconomyShop(ctx, boil.GetContextDB(), guildID, name, soldby, selectCols...)
}

// FindEconomyShop retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEconomyShop(ctx context.Context, exec boil.ContextExecutor, guildID string, name string, soldby string, selectCols ...string) (*EconomyShop, error) {
	economyShopObj := &EconomyShop{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"economy_shop\" where \"guild_id\"=$1 AND \"name\"=$2 AND \"soldby\"=$3", sel,
	)

	q := queries.Raw(query, guildID, name, soldby)

	err := q.Bind(ctx, exec, economyShopObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from economy_shop")
	}

	return economyShopObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *EconomyShop) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EconomyShop) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_shop provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(economyShopColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	economyShopInsertCacheMut.RLock()
	cache, cached := economyShopInsertCache[key]
	economyShopInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			economyShopAllColumns,
			economyShopColumnsWithDefault,
			economyShopColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(economyShopType, economyShopMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(economyShopType, economyShopMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"economy_shop\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"economy_shop\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into economy_shop")
	}

	if !cached {
		economyShopInsertCacheMut.Lock()
		economyShopInsertCache[key] = cache
		economyShopInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single EconomyShop record using the global executor.
// See Update for more documentation.
func (o *EconomyShop) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the EconomyShop.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EconomyShop) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	economyShopUpdateCacheMut.RLock()
	cache, cached := economyShopUpdateCache[key]
	economyShopUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			economyShopAllColumns,
			economyShopPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update economy_shop, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"economy_shop\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, economyShopPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(economyShopType, economyShopMapping, append(wl, economyShopPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update economy_shop row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for economy_shop")
	}

	if !cached {
		economyShopUpdateCacheMut.Lock()
		economyShopUpdateCache[key] = cache
		economyShopUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q economyShopQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q economyShopQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for economy_shop")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for economy_shop")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o EconomyShopSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EconomyShopSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyShopPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"economy_shop\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, economyShopPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in economyShop slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all economyShop")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *EconomyShop) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EconomyShop) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no economy_shop provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(economyShopColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	economyShopUpsertCacheMut.RLock()
	cache, cached := economyShopUpsertCache[key]
	economyShopUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			economyShopAllColumns,
			economyShopColumnsWithDefault,
			economyShopColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			economyShopAllColumns,
			economyShopPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert economy_shop, could not build update column list")
		}

		ret := strmangle.SetComplement(economyShopAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(economyShopPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert economy_shop, could not build conflict column list")
			}

			conflict = make([]string, len(economyShopPrimaryKeyColumns))
			copy(conflict, economyShopPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"economy_shop\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(economyShopType, economyShopMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(economyShopType, economyShopMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert economy_shop")
	}

	if !cached {
		economyShopUpsertCacheMut.Lock()
		economyShopUpsertCache[key] = cache
		economyShopUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single EconomyShop record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *EconomyShop) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single EconomyShop record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EconomyShop) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EconomyShop provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), economyShopPrimaryKeyMapping)
	sql := "DELETE FROM \"economy_shop\" WHERE \"guild_id\"=$1 AND \"name\"=$2 AND \"soldby\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from economy_shop")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for economy_shop")
	}

	return rowsAff, nil
}

func (q economyShopQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q economyShopQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no economyShopQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economy_shop")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_shop")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o EconomyShopSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EconomyShopSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyShopPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"economy_shop\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyShopPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economyShop slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_shop")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *EconomyShop) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no EconomyShop provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EconomyShop) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEconomyShop(ctx, exec, o.GuildID, o.Name, o.Soldby)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyShopSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty EconomyShopSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyShopSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EconomyShopSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyShopPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"economy_shop\".* FROM \"economy_shop\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyShopPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EconomyShopSlice")
	}

	*o = slice

	return nil
}

// EconomyShopExistsG checks if the EconomyShop row exists.
func EconomyShopExistsG(ctx context.Context, guildID string, name string, soldby string) (bool, error) {
	return EconomyShopExists(ctx, boil.GetContextDB(), guildID, name, soldby)
}

// EconomyShopExists checks if the EconomyShop row exists.
func EconomyShopExists(ctx context.Context, exec boil.ContextExecutor, guildID string, name string, soldby string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"economy_shop\" where \"guild_id\"=$1 AND \"name\"=$2 AND \"soldby\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID, name, soldby)
	}
	row := exec.QueryRowContext(ctx, sql, guildID, name, soldby)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if economy_shop exists")
	}

	return exists, nil
}

// Exists checks if the EconomyShop row exists.
func (o *EconomyShop) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EconomyShopExists(ctx, exec, o.GuildID, o.Name, o.Soldby)
}
