// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EconomyCustomResponse is an object representing the database table.
type EconomyCustomResponse struct {
	GuildID  string `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	Type     string `boil:"type" json:"type" toml:"type" yaml:"type"`
	Response string `boil:"response" json:"response" toml:"response" yaml:"response"`

	R *economyCustomResponseR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L economyCustomResponseL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EconomyCustomResponseColumns = struct {
	GuildID  string
	Type     string
	Response string
}{
	GuildID:  "guild_id",
	Type:     "type",
	Response: "response",
}

var EconomyCustomResponseTableColumns = struct {
	GuildID  string
	Type     string
	Response string
}{
	GuildID:  "economy_custom_responses.guild_id",
	Type:     "economy_custom_responses.type",
	Response: "economy_custom_responses.response",
}

// Generated where

var EconomyCustomResponseWhere = struct {
	GuildID  whereHelperstring
	Type     whereHelperstring
	Response whereHelperstring
}{
	GuildID:  whereHelperstring{field: "\"economy_custom_responses\".\"guild_id\""},
	Type:     whereHelperstring{field: "\"economy_custom_responses\".\"type\""},
	Response: whereHelperstring{field: "\"economy_custom_responses\".\"response\""},
}

// EconomyCustomResponseRels is where relationship names are stored.
var EconomyCustomResponseRels = struct {
	Guild string
}{
	Guild: "Guild",
}

// economyCustomResponseR is where relationships are stored.
type economyCustomResponseR struct {
	Guild *EconomyConfig `boil:"Guild" json:"Guild" toml:"Guild" yaml:"Guild"`
}

// NewStruct creates a new relationship struct
func (*economyCustomResponseR) NewStruct() *economyCustomResponseR {
	return &economyCustomResponseR{}
}

func (o *EconomyCustomResponse) GetGuild() *EconomyConfig {
	if o == nil {
		return nil
	}

	return o.R.GetGuild()
}

func (r *economyCustomResponseR) GetGuild() *EconomyConfig {
	if r == nil {
		return nil
	}

	return r.Guild
}

// economyCustomResponseL is where Load methods for each relationship are stored.
type economyCustomResponseL struct{}

var (
	economyCustomResponseAllColumns            = []string{"guild_id", "type", "response"}
	economyCustomResponseColumnsWithoutDefault = []string{"guild_id", "type", "response"}
	economyCustomResponseColumnsWithDefault    = []string{}
	economyCustomResponsePrimaryKeyColumns     = []string{"guild_id"}
	economyCustomResponseGeneratedColumns      = []string{}
)

type (
	// EconomyCustomResponseSlice is an alias for a slice of pointers to EconomyCustomResponse.
	// This should almost always be used instead of []EconomyCustomResponse.
	EconomyCustomResponseSlice []*EconomyCustomResponse

	economyCustomResponseQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	economyCustomResponseType                 = reflect.TypeOf(&EconomyCustomResponse{})
	economyCustomResponseMapping              = queries.MakeStructMapping(economyCustomResponseType)
	economyCustomResponsePrimaryKeyMapping, _ = queries.BindMapping(economyCustomResponseType, economyCustomResponseMapping, economyCustomResponsePrimaryKeyColumns)
	economyCustomResponseInsertCacheMut       sync.RWMutex
	economyCustomResponseInsertCache          = make(map[string]insertCache)
	economyCustomResponseUpdateCacheMut       sync.RWMutex
	economyCustomResponseUpdateCache          = make(map[string]updateCache)
	economyCustomResponseUpsertCacheMut       sync.RWMutex
	economyCustomResponseUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single economyCustomResponse record from the query using the global executor.
func (q economyCustomResponseQuery) OneG(ctx context.Context) (*EconomyCustomResponse, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single economyCustomResponse record from the query.
func (q economyCustomResponseQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EconomyCustomResponse, error) {
	o := &EconomyCustomResponse{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for economy_custom_responses")
	}

	return o, nil
}

// AllG returns all EconomyCustomResponse records from the query using the global executor.
func (q economyCustomResponseQuery) AllG(ctx context.Context) (EconomyCustomResponseSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all EconomyCustomResponse records from the query.
func (q economyCustomResponseQuery) All(ctx context.Context, exec boil.ContextExecutor) (EconomyCustomResponseSlice, error) {
	var o []*EconomyCustomResponse

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EconomyCustomResponse slice")
	}

	return o, nil
}

// CountG returns the count of all EconomyCustomResponse records in the query using the global executor
func (q economyCustomResponseQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all EconomyCustomResponse records in the query.
func (q economyCustomResponseQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count economy_custom_responses rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q economyCustomResponseQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q economyCustomResponseQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if economy_custom_responses exists")
	}

	return count > 0, nil
}

// Guild pointed to by the foreign key.
func (o *EconomyCustomResponse) Guild(mods ...qm.QueryMod) economyConfigQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"guild_id\" = ?", o.GuildID),
	}

	queryMods = append(queryMods, mods...)

	return EconomyConfigs(queryMods...)
}

// LoadGuild allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (economyCustomResponseL) LoadGuild(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEconomyCustomResponse interface{}, mods queries.Applicator) error {
	var slice []*EconomyCustomResponse
	var object *EconomyCustomResponse

	if singular {
		var ok bool
		object, ok = maybeEconomyCustomResponse.(*EconomyCustomResponse)
		if !ok {
			object = new(EconomyCustomResponse)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEconomyCustomResponse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEconomyCustomResponse))
			}
		}
	} else {
		s, ok := maybeEconomyCustomResponse.(*[]*EconomyCustomResponse)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEconomyCustomResponse)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEconomyCustomResponse))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &economyCustomResponseR{}
		}
		args[object.GuildID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &economyCustomResponseR{}
			}

			args[obj.GuildID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`economy_config`),
		qm.WhereIn(`economy_config.guild_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load EconomyConfig")
	}

	var resultSlice []*EconomyConfig
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice EconomyConfig")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for economy_config")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for economy_config")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Guild = foreign
		if foreign.R == nil {
			foreign.R = &economyConfigR{}
		}
		foreign.R.GuildEconomyCustomResponse = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GuildID == foreign.GuildID {
				local.R.Guild = foreign
				if foreign.R == nil {
					foreign.R = &economyConfigR{}
				}
				foreign.R.GuildEconomyCustomResponse = local
				break
			}
		}
	}

	return nil
}

// SetGuildG of the economyCustomResponse to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildEconomyCustomResponse.
// Uses the global database handle.
func (o *EconomyCustomResponse) SetGuildG(ctx context.Context, insert bool, related *EconomyConfig) error {
	return o.SetGuild(ctx, boil.GetContextDB(), insert, related)
}

// SetGuild of the economyCustomResponse to the related item.
// Sets o.R.Guild to related.
// Adds o to related.R.GuildEconomyCustomResponse.
func (o *EconomyCustomResponse) SetGuild(ctx context.Context, exec boil.ContextExecutor, insert bool, related *EconomyConfig) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"economy_custom_responses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"guild_id"}),
		strmangle.WhereClause("\"", "\"", 2, economyCustomResponsePrimaryKeyColumns),
	)
	values := []interface{}{related.GuildID, o.GuildID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GuildID = related.GuildID
	if o.R == nil {
		o.R = &economyCustomResponseR{
			Guild: related,
		}
	} else {
		o.R.Guild = related
	}

	if related.R == nil {
		related.R = &economyConfigR{
			GuildEconomyCustomResponse: o,
		}
	} else {
		related.R.GuildEconomyCustomResponse = o
	}

	return nil
}

// EconomyCustomResponses retrieves all the records using an executor.
func EconomyCustomResponses(mods ...qm.QueryMod) economyCustomResponseQuery {
	mods = append(mods, qm.From("\"economy_custom_responses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"economy_custom_responses\".*"})
	}

	return economyCustomResponseQuery{q}
}

// FindEconomyCustomResponseG retrieves a single record by ID.
func FindEconomyCustomResponseG(ctx context.Context, guildID string, selectCols ...string) (*EconomyCustomResponse, error) {
	return FindEconomyCustomResponse(ctx, boil.GetContextDB(), guildID, selectCols...)
}

// FindEconomyCustomResponse retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEconomyCustomResponse(ctx context.Context, exec boil.ContextExecutor, guildID string, selectCols ...string) (*EconomyCustomResponse, error) {
	economyCustomResponseObj := &EconomyCustomResponse{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"economy_custom_responses\" where \"guild_id\"=$1", sel,
	)

	q := queries.Raw(query, guildID)

	err := q.Bind(ctx, exec, economyCustomResponseObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from economy_custom_responses")
	}

	return economyCustomResponseObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *EconomyCustomResponse) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EconomyCustomResponse) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_custom_responses provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(economyCustomResponseColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	economyCustomResponseInsertCacheMut.RLock()
	cache, cached := economyCustomResponseInsertCache[key]
	economyCustomResponseInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			economyCustomResponseAllColumns,
			economyCustomResponseColumnsWithDefault,
			economyCustomResponseColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(economyCustomResponseType, economyCustomResponseMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(economyCustomResponseType, economyCustomResponseMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"economy_custom_responses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"economy_custom_responses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into economy_custom_responses")
	}

	if !cached {
		economyCustomResponseInsertCacheMut.Lock()
		economyCustomResponseInsertCache[key] = cache
		economyCustomResponseInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single EconomyCustomResponse record using the global executor.
// See Update for more documentation.
func (o *EconomyCustomResponse) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the EconomyCustomResponse.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EconomyCustomResponse) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	economyCustomResponseUpdateCacheMut.RLock()
	cache, cached := economyCustomResponseUpdateCache[key]
	economyCustomResponseUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			economyCustomResponseAllColumns,
			economyCustomResponsePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update economy_custom_responses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"economy_custom_responses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, economyCustomResponsePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(economyCustomResponseType, economyCustomResponseMapping, append(wl, economyCustomResponsePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update economy_custom_responses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for economy_custom_responses")
	}

	if !cached {
		economyCustomResponseUpdateCacheMut.Lock()
		economyCustomResponseUpdateCache[key] = cache
		economyCustomResponseUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q economyCustomResponseQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q economyCustomResponseQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for economy_custom_responses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for economy_custom_responses")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o EconomyCustomResponseSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EconomyCustomResponseSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyCustomResponsePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"economy_custom_responses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, economyCustomResponsePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in economyCustomResponse slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all economyCustomResponse")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *EconomyCustomResponse) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EconomyCustomResponse) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no economy_custom_responses provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(economyCustomResponseColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	economyCustomResponseUpsertCacheMut.RLock()
	cache, cached := economyCustomResponseUpsertCache[key]
	economyCustomResponseUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			economyCustomResponseAllColumns,
			economyCustomResponseColumnsWithDefault,
			economyCustomResponseColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			economyCustomResponseAllColumns,
			economyCustomResponsePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert economy_custom_responses, could not build update column list")
		}

		ret := strmangle.SetComplement(economyCustomResponseAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(economyCustomResponsePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert economy_custom_responses, could not build conflict column list")
			}

			conflict = make([]string, len(economyCustomResponsePrimaryKeyColumns))
			copy(conflict, economyCustomResponsePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"economy_custom_responses\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(economyCustomResponseType, economyCustomResponseMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(economyCustomResponseType, economyCustomResponseMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert economy_custom_responses")
	}

	if !cached {
		economyCustomResponseUpsertCacheMut.Lock()
		economyCustomResponseUpsertCache[key] = cache
		economyCustomResponseUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single EconomyCustomResponse record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *EconomyCustomResponse) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single EconomyCustomResponse record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EconomyCustomResponse) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EconomyCustomResponse provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), economyCustomResponsePrimaryKeyMapping)
	sql := "DELETE FROM \"economy_custom_responses\" WHERE \"guild_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from economy_custom_responses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for economy_custom_responses")
	}

	return rowsAff, nil
}

func (q economyCustomResponseQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q economyCustomResponseQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no economyCustomResponseQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economy_custom_responses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_custom_responses")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o EconomyCustomResponseSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EconomyCustomResponseSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyCustomResponsePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"economy_custom_responses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyCustomResponsePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economyCustomResponse slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_custom_responses")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *EconomyCustomResponse) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no EconomyCustomResponse provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EconomyCustomResponse) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEconomyCustomResponse(ctx, exec, o.GuildID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyCustomResponseSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty EconomyCustomResponseSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyCustomResponseSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EconomyCustomResponseSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyCustomResponsePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"economy_custom_responses\".* FROM \"economy_custom_responses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyCustomResponsePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EconomyCustomResponseSlice")
	}

	*o = slice

	return nil
}

// EconomyCustomResponseExistsG checks if the EconomyCustomResponse row exists.
func EconomyCustomResponseExistsG(ctx context.Context, guildID string) (bool, error) {
	return EconomyCustomResponseExists(ctx, boil.GetContextDB(), guildID)
}

// EconomyCustomResponseExists checks if the EconomyCustomResponse row exists.
func EconomyCustomResponseExists(ctx context.Context, exec boil.ContextExecutor, guildID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"economy_custom_responses\" where \"guild_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID)
	}
	row := exec.QueryRowContext(ctx, sql, guildID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if economy_custom_responses exists")
	}

	return exists, nil
}

// Exists checks if the EconomyCustomResponse row exists.
func (o *EconomyCustomResponse) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EconomyCustomResponseExists(ctx, exec, o.GuildID)
}
