#!/bin/bash

export ASBWIG_TOKEN="tokenXXXX"
export ASBWIG_PGHOST="localhost"
export ASBWIG_PGDB="asbwig"
export ASBWIG_PGUSER="asbwig"
export ASBWIG_CLIENTID="clientID"
export ASBWIG_CLIENTSECRET="secretXXXX"
export ASBWIG_HOST="your domain here"